// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20231129055857_UserService-update-defaultNull-Username")]
    partial class UserServiceupdatedefaultNullUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ClassroomInfor", b =>
                {
                    b.Property<string>("IdUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdClassroom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.Property<string>("LinkAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUser", "IdClassroom");

                    b.ToTable("ClassroomInfor", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = "193ba283-bf34-40ad-a3be-10b1780cba0e",
                            IdClassroom = "ee546ce7-842a-4dee-86d0-0db1ff3b64b4",
                            Avatar = "",
                            Description = "",
                            IsHost = true,
                            LinkAvatar = "",
                            Name = "Class_1"
                        },
                        new
                        {
                            IdUser = "2c75293b-f8e5-4862-9b13-5894a64895cd",
                            IdClassroom = "0a006921-b4a4-40de-a1e6-9497daf09a2f",
                            Avatar = "",
                            Description = "",
                            IsHost = true,
                            LinkAvatar = "",
                            Name = "Class_2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "849a0fed-3ecf-4655-bc31-6c65e166395e",
                            Description = "",
                            Name = "ADMIN",
                            NormalizeName = "Admin"
                        },
                        new
                        {
                            Id = "cd2676e0-0861-472b-be14-32de8e39e01e",
                            Description = "",
                            Name = "USER",
                            NormalizeName = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinkAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PresentEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TokenAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            id = "193ba283-bf34-40ad-a3be-10b1780cba0e",
                            Avatar = "",
                            Birthday = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5483),
                            CreatedDate = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5494),
                            FirstEmail = "test001@gmail.com",
                            FirstName = "test",
                            IsLock = false,
                            IsVerified = true,
                            LastName = "account",
                            LinkAvatar = "",
                            PasswordHash = "nSUQ/133didCpNJLsvcLvQ==",
                            PhoneNumber = "0123456789",
                            PresentEmail = "test001@gmail.com",
                            RoleId = "cd2676e0-0861-472b-be14-32de8e39e01e",
                            TokenAccess = "3A3AB8676FE9D10C9E9E3B4E6C8505E74FB8F3940AE9223C0E1536EBA02E7CB2E185C108A503E76734A98E55D03FE364415C01391EE323C6C718354BCF1C74CE",
                            UserName = "testVersion_0001",
                            VerifiedDate = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5547)
                        },
                        new
                        {
                            id = "2c75293b-f8e5-4862-9b13-5894a64895cd",
                            Avatar = "",
                            Birthday = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5696),
                            CreatedDate = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5697),
                            FirstEmail = "admin001@gmail.com",
                            FirstName = "Admin",
                            IsLock = false,
                            IsVerified = true,
                            LastName = "account",
                            LinkAvatar = "",
                            PasswordHash = "VWBU8/+H4em26o8A92n+Tg==",
                            PhoneNumber = "0123456789",
                            PresentEmail = "admin001@gmail.com",
                            RoleId = "849a0fed-3ecf-4655-bc31-6c65e166395e",
                            TokenAccess = "E8EB138CEC24407BC3917AAFB050CA0C5B2547D29458457FE378AA86DD709B5F12CFE9FB4202A38FE1651A0BC08583BC3C6D757C42E527C1DC43CE18219359D4",
                            UserName = "adminVersion_0001",
                            VerifiedDate = new DateTime(2023, 11, 29, 12, 58, 57, 424, DateTimeKind.Local).AddTicks(5702)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClassroomInfor", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ListClassroomInfor")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ListClassroomInfor");
                });
#pragma warning restore 612, 618
        }
    }
}
