// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    partial class UserServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ClassroomInfor", b =>
                {
                    b.Property<string>("IdUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdClassroom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.Property<string>("LinkAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUser", "IdClassroom");

                    b.ToTable("ClassroomInfor", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = "193ba283-bf34-40ad-a3be-10b1780cba0e",
                            IdClassroom = "ee546ce7-842a-4dee-86d0-0db1ff3b64b4",
                            Avatar = "",
                            Description = "",
                            IsHost = true,
                            LinkAvatar = "",
                            Name = "Class_1"
                        },
                        new
                        {
                            IdUser = "2c75293b-f8e5-4862-9b13-5894a64895cd",
                            IdClassroom = "0a006921-b4a4-40de-a1e6-9497daf09a2f",
                            Avatar = "",
                            Description = "",
                            IsHost = true,
                            LinkAvatar = "",
                            Name = "Class_2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6c397b90-c8e4-40db-8e49-49ab3f0bda64",
                            Description = "",
                            Name = "ADMIN",
                            NormalizeName = "Admin"
                        },
                        new
                        {
                            Id = "11750602-8c16-40d1-8991-4fefc0858b40",
                            Description = "",
                            Name = "USER",
                            NormalizeName = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinkAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PresentEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TokenAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            id = "193ba283-bf34-40ad-a3be-10b1780cba0e",
                            Avatar = "",
                            Birthday = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6172),
                            CreatedDate = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6183),
                            FirstEmail = "test001@gmail.com",
                            FirstName = "test",
                            IsLock = false,
                            IsVerified = true,
                            LastName = "account",
                            LinkAvatar = "",
                            PasswordHash = "nSUQ/133didCpNJLsvcLvQ==",
                            PhoneNumber = "0123456789",
                            PresentEmail = "test001@gmail.com",
                            RoleId = "11750602-8c16-40d1-8991-4fefc0858b40",
                            TokenAccess = "5F5A5B09CAC68E3090D3DDE024B40DAEC657E332A182C4020407C2CA0CA1E3D1C4374853223A9E325D10C7CD09AE600EECE97B34CB451D4D1BA95BED98A5E47D",
                            UserName = "testVersion_0001",
                            VerifiedDate = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6238)
                        },
                        new
                        {
                            id = "2c75293b-f8e5-4862-9b13-5894a64895cd",
                            Avatar = "",
                            Birthday = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6328),
                            CreatedDate = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6328),
                            FirstEmail = "admin001@gmail.com",
                            FirstName = "Admin",
                            IsLock = false,
                            IsVerified = true,
                            LastName = "account",
                            LinkAvatar = "",
                            PasswordHash = "VWBU8/+H4em26o8A92n+Tg==",
                            PhoneNumber = "0123456789",
                            PresentEmail = "admin001@gmail.com",
                            RoleId = "6c397b90-c8e4-40db-8e49-49ab3f0bda64",
                            TokenAccess = "20BEEC96FCFF4507D35B65D18952FEF9913531418A3EBF0B68A2128FB2864697EED308F3A4F0AACDDA59A1907FA0D53065CC658D61C1254C453A5745622B1FA1",
                            UserName = "adminVersion_0001",
                            VerifiedDate = new DateTime(2023, 11, 16, 10, 43, 11, 675, DateTimeKind.Local).AddTicks(6334)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClassroomInfor", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ListClassroomInfor")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ListClassroomInfor");
                });
#pragma warning restore 612, 618
        }
    }
}
